export const ALL_SERVICES = [
  {
    id: 1,
    title: "Deep Cleaning",
    category: "Home Care",
    badge: "POPULAR",
    description: "Medical-grade sanitation and meticulously detailed cleaning for residential and office spaces.",
    price: "$89",
    unit: "hr",
    rating: 4.9,
    image: "home_repair",
    route: "/service/cleaning",
    icon: "🧹",
  },
  {
    id: 2,
    title: "Master Plumbing",
    category: "Home Care",
    description: "Emergency leak repairs, pipe infrastructure maintenance, and high-end fixture installation.",
    price: "$120",
    unit: "hr",
    rating: 4.8,
    image: "plumbing",
    route: "/service/plumbing",
    icon: "🔧",
  },
  {
    id: 3,
    title: "Smart Electrical",
    category: "Home Care",
    description: "Expert wiring for smart homes, industrial electrical audits, and lighting system overhauls.",
    price: "$150",
    unit: "hr",
    rating: 4.9,
    image: "electrical",
    route: "/service/electrical",
    icon: "⚡",
  },
  {
    id: 4,
    title: "HVAC Systems",
    category: "Commercial",
    description: "Precision climate control maintenance, filter sterilization, and full system installs.",
    price: "$110",
    unit: "hr",
    rating: 4.7,
    image: "home_repair",
    route: "/service/ac-repair",
    icon: "❄️",
  },
  {
    id: 5,
    title: "Garden Architecture",
    category: "Home Care",
    description: "Professional landscaping, vertical garden design, and intelligent irrigation maintenance.",
    price: "$95",
    unit: "hr",
    rating: 4.8,
    image: "flooring",
    route: "/service/landscaping",
    icon: "🌿",
  },
  {
    id: 6,
    title: "Security Audit",
    category: "Commercial",
    description: "Full property security assessments, smart lock deployment, and CCTV surveillance networks.",
    price: "$180",
    unit: "ea",
    rating: 5.0,
    image: "electrical",
    route: "/service/home-repair",
    icon: "🔒",
  },
];
